version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    image: jiggins89/hello-world-rails:1.0
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
