version: '3'
services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      # POSTGRES_DB: db
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: password

  web:
    image: jiggins89/hello-world-rails-prod:2.0
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
    deploy: 
      replicas: 3

networks:
  app-network:

volumes: 
  db-data:
  